/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as BibliaIndexRouteImport } from './routes/biblia.index'
import { Route as EstudiosIndexRouteImport } from './routes/estudios.index'
import { Route as BibliaBookIdIndexRouteImport } from './routes/biblia.$bookId.index'
import { Route as BibliaBookIdChapterRouteImport } from './routes/biblia.$bookId.$chapter'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliaIndexRoute = BibliaIndexRouteImport.update({
  id: '/biblia/',
  path: '/biblia/',
  getParentRoute: () => rootRouteImport,
} as any)
const EstudiosIndexRoute = EstudiosIndexRouteImport.update({
  id: '/estudios/',
  path: '/estudios/',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliaBookIdIndexRoute = BibliaBookIdIndexRouteImport.update({
  id: '/biblia/$bookId/',
  path: '/biblia/$bookId/',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliaBookIdChapterRoute = BibliaBookIdChapterRouteImport.update({
  id: '/biblia/$bookId/$chapter',
  path: '/biblia/$bookId/$chapter',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/biblia/': typeof BibliaIndexRoute
  '/estudios/': typeof EstudiosIndexRoute
  '/biblia/$bookId/$chapter': typeof BibliaBookIdChapterRoute
  '/biblia/$bookId/': typeof BibliaBookIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/biblia': typeof BibliaIndexRoute
  '/estudios': typeof EstudiosIndexRoute
  '/biblia/$bookId/$chapter': typeof BibliaBookIdChapterRoute
  '/biblia/$bookId': typeof BibliaBookIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/biblia/': typeof BibliaIndexRoute
  '/estudios/': typeof EstudiosIndexRoute
  '/biblia/$bookId/$chapter': typeof BibliaBookIdChapterRoute
  '/biblia/$bookId/': typeof BibliaBookIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buscar'
    | '/biblia/'
    | '/estudios/'
    | '/biblia/$bookId/$chapter'
    | '/biblia/$bookId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buscar'
    | '/biblia'
    | '/estudios'
    | '/biblia/$bookId/$chapter'
    | '/biblia/$bookId'
  id:
    | '__root__'
    | '/'
    | '/buscar'
    | '/biblia/'
    | '/estudios/'
    | '/biblia/$bookId/$chapter'
    | '/biblia/$bookId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuscarRoute: typeof BuscarRoute
  BibliaIndexRoute: typeof BibliaIndexRoute
  EstudiosIndexRoute: typeof EstudiosIndexRoute
  BibliaBookIdChapterRoute: typeof BibliaBookIdChapterRoute
  BibliaBookIdIndexRoute: typeof BibliaBookIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblia/': {
      id: '/biblia/'
      path: '/biblia'
      fullPath: '/biblia/'
      preLoaderRoute: typeof BibliaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudios/': {
      id: '/estudios/'
      path: '/estudios'
      fullPath: '/estudios/'
      preLoaderRoute: typeof EstudiosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblia/$bookId/': {
      id: '/biblia/$bookId/'
      path: '/biblia/$bookId'
      fullPath: '/biblia/$bookId/'
      preLoaderRoute: typeof BibliaBookIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblia/$bookId/$chapter': {
      id: '/biblia/$bookId/$chapter'
      path: '/biblia/$bookId/$chapter'
      fullPath: '/biblia/$bookId/$chapter'
      preLoaderRoute: typeof BibliaBookIdChapterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuscarRoute: BuscarRoute,
  BibliaIndexRoute: BibliaIndexRoute,
  EstudiosIndexRoute: EstudiosIndexRoute,
  BibliaBookIdChapterRoute: BibliaBookIdChapterRoute,
  BibliaBookIdIndexRoute: BibliaBookIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
